#!/usr/bin/env bash
####################
deb_file_installer_tui_or_gui() {
    check_imagemagick
    if (whiptail --title "GUI or TUI" --yes-button "GUI" --no-button "TUI" --yesno "您是想用图形用户界面,还是文本用户界面呢？\nDo you want to use GUI or GUI?\n若您处于桌面环境下,则建议选择GUI,否则请选择TUI♪(^∇^*) " 0 0); then
        gui_image_compression_tool
    else
        tui_image_compression_tool
    fi
}
#################
deb_file_installer() {
    #进入deb文件目录
    cd ${CURRENT_DIR}
    #./${SELECTION}
    if [ "${LINUX_DISTRO}" = "debian" ]; then
        file ./${SELECTION} 2>/dev/null
        apt show ./${SELECTION}
        PACKAGE_NAME=$(apt show ./${SELECTION} 2>&1 | grep Package | head -n 1 | awk -F ' ' '$0=$NF')
        echo "您是否需要安装此软件包？"
        echo "Do you want to install it?"
        RETURN_TO_WHERE='remove_deb_package'
        do_you_want_to_continue
        RETURN_TO_WHERE='software_center'
        apt install -y ./${SELECTION}
        DEPENDENCY_01=${PACKAGE_NAME}
        DEPENDENCY_02=""
        beta_features_install_completed
    else
        if [ ! $(command -v dpkg) ]; then
            DEPENDENCY_01='dpkg'
            DEPENDENCY_02=''
            echo ${TMOE_INSTALLATON_COMMAND} ${DEPENDENCY_01}
            ${TMOE_INSTALLATON_COMMAND} ${DEPENDENCY_01}
            beta_features_install_completed
        fi
        if [ $(command -v dpkg) ]; then
            dpkg -i ./${SELECTION}
        else
            uncompress_deb_file
        fi
    fi
    delete_tmoe_deb_file
}
######################
uncompress_deb_file() {
    mkdir -p .DEB_TEMP_FOLDER
    mv ${SELECTION} .DEB_TEMP_FOLDER
    cd ./.DEB_TEMP_FOLDER
    if [ "${BUSYBOX_AR}" = 'true' ]; then
        busybox ar xv ${SELECTION}
    else
        ar xv ${SELECTION}
    fi
    mv ${SELECTION} ../
    if [ -e "data.tar.xz" ]; then
        cd /
        tar -Jxvf ${CURRENT_DIR}/.DEB_TEMP_FOLDER/data.tar.xz ./usr
    elif [ -e "data.tar.gz" ]; then
        cd /
        tar -zxvf ${CURRENT_DIR}/.DEB_TEMP_FOLDER/data.tar.gz ./usr
    fi
    rm -rf ${CURRENT_DIR}/.DEB_TEMP_FOLDER
}
########################
delete_tmoe_deb_file() {
    echo "请问是否需要${RED}删除${RESET}安装包文件"
    ls -lah ${TMOE_FILE_ABSOLUTE_PATH}
    echo "Do you want to ${RED}delete${RESET} it?"
    do_you_want_to_continue
    rm -fv ${TMOE_FILE_ABSOLUTE_PATH}
}
#################
remove_deb_package() {
    if (whiptail --title "您想要对这个小可爱做什么呢 " --yes-button "Back返回" --no-button "Remove移除" --yesno "${PACKAGE_NAME}\n您是想要返回还是卸载这个软件包？Do you want to return,or remove this package?♪(^∇^*) " 10 50); then
        software_center
    else
        apt purge ${PACKAGE_NAME}
        delete_tmoe_deb_file
        software_center
    fi
}
#############
tmoe_deb_file_installer() {
    FILE_EXT_01='deb'
    FILE_EXT_02='DEB'
    START_DIR="${HOME}"
    tmoe_file_manager
    if [ -z ${SELECTION} ]; then
        echo "没有指定${YELLOW}有效${RESET}的${BLUE}文件${GREEN}，请${GREEN}重新${RESET}选择"
    else
        echo "您选择的deb文件为${TMOE_FILE_ABSOLUTE_PATH}"
        ls -lah ${TMOE_FILE_ABSOLUTE_PATH}
        deb_file_installer
    fi
}
##################
