#!/usr/bin/env bash
. /etc/tigervnc/vncserver-config-defaults 2>/dev/null
unset "${@}"
set -- "${@}" ":${TMOE_VNC_DISPLAY_NUMBER}"
set -- "${@}" "-AlwaysShared"
set -- "${@}" "-ac"
set -- "${@}" "-geometry" "${geometry}"
set -- "${@}" "-desktop=${desktop}"
set -- "${@}" "-rfbauth=${HOME}/.vnc/passwd"
set -- "${@}" "-ZlibLevel=9"
set -- "Xvnc" "$@"
exec "$@" &
exec /etc/X11/xinit/Xsession &
exit 0
