#!/usr/bin/env bash
########################
development_programming_tools() {
    RETURN_TO_WHERE='development_programming_tools'
    SOFTWARE=$(
        whiptail --title "Development" --menu \
            "您想要安装哪个软件？\n Which software do you want to install?" 0 50 0 \
            "1" "🇻 🇸 VSCode 现代化代码编辑器" \
            "2" "🇦 🇸 Android-Studio(安卓开发工具IDE)" \
            "3" "🇮 🇯 IntelliJ IDEA(java编程语言集成开发环境)" \
            "4" "🇵 🇾 PyCharm(python集成开发环境)" \
            "5" "🇼 🇸 Webstorm(JavaScript IDE,Web前端开发工具)" \
            "6" "🇨 🇱 CLion(C/C++集成开发环境)" \
            "7" "🇬 🇴 GoLand(JetBrains的Go开发工具)" \
            "8" "🇹 🇨 teamcity(持续集成Continue Integration工具)" \
            "9" "♐ github-desktop(x64,github官方桌面客户端)" \
            "10" "⚛️ atom(x64,类Sublime风格文本编辑器，github出品)" \
            "0" "🌚 Return to previous menu 返回上级菜单" \
            3>&1 1>&2 2>&3
    )
    case "${SOFTWARE}" in
    0 | "") software_center ;;
    1) which_vscode_edition ;;
    2) install_android_studio ;;
    *) echo "新版即将集成本开发工具的安装，敬请期待" ;;
    esac
       # 3) install_intellij_idea ;;
    ############################################
    press_enter_to_return
    development_programming_tools
}
###########
check_ide_version() {
    cat <<-ENDofTable
		╔═══╦══════════╦═══════════════════╦════════════════════
		║   ║          ║                   ║                    
		║   ║ software ║    ✨最新版本     ║   本地版本 🎪
		║   ║          ║  Latest version   ║  Local version     
		║---║----------║-------------------║--------------------
		║ 1 ║${GREP_NAME}                      ${LOCAL_OPT_APP_VERSION} 
		║   ║          ║${THE_LATEST_APP_VERSION_CODE}

	ENDofTable
}
#########
uncompress_arch_pkg_tar_zst() {
    mkdir -p ${APP_OPT_DIR}
    cd ${APP_OPT_DIR}
    tar --zstd -xvf ${DOWNLOAD_PATH}/${ARCH_WALLPAPER_VERSION} &>/dev/null || zstdcat "${DOWNLOAD_PATH}/${ARCH_WALLPAPER_VERSION}" | tar xvf -
    cp -pf ${TMOE_TOOL_DIR}/code/lnk/${GREP_NAME}.desktop ${APPS_LNK_DIR}
}
###########
install_intellij_idea() {
    GREP_NAME='intellij-idea-ultimate-edition'
    check_opt_dir_01
    echo "正在检测版本更新信息..."
    echo "本版本为旗舰版，如需下载社区版，则请手动打开${YELLOW}https://www.jetbrains.com/idea/download/download-thanks.html?platform=linux&code=IIC${RESET}"
    check_archlinux_cn_html_date
    check_download_path
    ############
    THE_LATEST_APP_VERSION_CODE=$(cat index.html | grep '.pkg.tar.zst' | grep -Ev '.xz.sig|.zst.sig' | grep -v '\-jre\-' | grep "${GREP_NAME}" | tail -n 1 | cut -d '=' -f 3 | cut -d '"' -f 2 | sed "s@${GREP_NAME}-@@g" | sed 's@.pkg.tar.zst@@')
    LOCAL_OPT_APP_VERSION=$(cat ${TMOE_GIT_DIR} | head -n 1)
    grep_arch_linux_pkg_04
    uncompress_arch_pkg_tar_zst
    install_java
    echo "安装完成，如需卸载，请输${RED}rm -rv${RESET}${BLUE}${APP_OPT_DIR} ${APPS_LNK_DIR}/${GREP_NAME}.desktop${RESET}"
}
##################
creat_android_studio_application_link() {
    cd ${APPS_LNK_DIR}
    #Icon=android-studio
    cat >android_studio.desktop <<-'EOF'
		[Desktop Entry]
		Name=Android Studio
		Type=Application
		Comment=Android Studio provides the fastest tools for building apps on every type of Android device.
		Exec=/opt/android-studio/bin/studio.sh %F
		Icon=/opt/android-studio/bin/studio.svg
		Categories=TextEditor;Development;IDE;
		MimeType=text/plain;inode/directory;
		Terminal=false
		Actions=new-empty-window;
		StartupNotify=true
		StartupWMClass=Android-Studio
	EOF
    chmod a+r android_studio.desktop
}
#########################
download_android_studio() {
    THE_LATEST_DEB_LINK="$(curl -Lv 'https://developer.android.google.cn/studio/#downloads' | grep 'linux' | grep href | grep studio | tail -n 1 | cut -d '"' -f 2)"
    echo ${THE_LATEST_DEB_LINK}
    echo "Do you want to download and install it?"
    do_you_want_to_continue
    aria2c --allow-overwrite=true -s 10 -x 10 -k 1M -o android_studio_linux_64bit.tar.gz ${THE_LATEST_DEB_LINK}
}
###############
check_android_studio() {
    mkdir -p ${HOME}/sd/Download
    cd ${HOME}/sd/Download
    if [ -e "/opt/android-studio" ]; then
        echo '您已安装Android studio'
        echo "若您需要卸载，则请输${RED}rm -rv${RESET} ${HOME}/sd/Download/android_studio_linux_64bit.tar.gz ${BLUE}/opt/android-studio ${APPS_LNK_DIR}/android_studio.desktop${RESET};${RED}${TMOE_REMOVAL_COMMAND}${RESET} ${BLUE}default-jre${RESET}"
        echo "是否需要重新安装？"
        echo "Do you want to reinstall it?"
        do_you_want_to_continue
    fi
    if [ ! -e "android_studio_linux_64bit.tar.gz" ]; then
        download_android_studio
    fi
    install_java
}
##############
install_android_studio() {
    check_android_studio
    tar -zxvf android_studio_linux_64bit.tar.gz -C /opt
    creat_android_studio_application_link
    echo "安装包位于${BLUE}${HOME}/sd/Download/android_studio_linux_64bit.tar.gz${RESET}"
    echo "安装完成，如需卸载，则请输${RED}rm -rv${RESET} ${BLUE}/opt/android-studio ${APPS_LNK_DIR}/android_studio.desktop${RESET};${RED}${TMOE_REMOVAL_COMMAND}${RESET} ${BLUE}default-jre${RESET}"
}
##################
development_programming_tools
